

services:
  model:
    build: ./model
    ports:
      - "8001:8000"
    networks:
      - ultron

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - ultron
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - ultron
    environment:
      - MODEL_SERVICE_URL=http://model:8000
      - API_KEY=ultron-secret-key-12345 # Set a strong API key 


networks:  
  ultron:
    driver: bridge